### ISSUE TITLE
TypeError: Cannot read properties of undefined

### ISSUE THREAD

**Issue by programspace** [nicolasprigent/Dokuwiki-Copycode-plugin#18]
Hello. Thank you for developing this good plugin.

I want to use this plugin in my dokuwiki but it doesn’t work properly (cannot copy text in `<code></code>`area).

I think  it's because my dokuwiki is running under an HTTP environment or running under a local environment (navigator.clipboard problem or something).

Could you please tell me what caused this and how to fix it except for AOSSL?

 Here is MS Edge error console log.

---

js.php?t=bootstrap3&…  Uncaught TypeError: Cannot read properties of undefined (reading 'highlightedcopied')

 at new CopyHighlighted (js.php?t=bootstrap3…)
 at HTMLPreElement.<anonymous> (js.php?t=bootstrap3…)
at HTMLPreElement.dispatch (jquery.php?…)
at y.handle (jquery.php?…)

---

**Comment by nicolasprigent** [comment]
hello @programspace I've tested on my local installation, it works on both edge and chrome. Do you see the problem only on local installation or also on hosted address ?
If you only use dokuwiki as a local installation, you should try using the dokuwiki on a stick installation https://www.dokuwiki.org/install:dokuwiki_on_a_stick ? It works on my computer like a charm, doesn't need any server configuration it just works.

**Comment by programspace** [comment]
Thank you for your kind cooperation.
And I apologize for my misleading sentence ("running under a local environment").
Actually my dokuwiki (dokuwiki on a stick) is running on intranet
(on hosted address, like "http://PCname:portNo") with a proxy.
For convenience, I don't set username and password of the proxy at dokuwiki 
(because of periodic password changes).

I checked the plugin perfectly worked  on local installation(localhost) environment as you say. (:-<
Is there any differences in localhost and hosted address in terms of working?

**Comment by nicolasprigent** [comment]
Hello, the documentation on this browser funtion [here](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/clipboard) says that it's only available on secure contexts HTTPS (and I guess localhost is considered secured also, even whitout HTTPS). 
![image](https://github.com/nicolasprigent/Dokuwiki-Copycode-plugin/assets/66468412/1f95ace7-37b8-4506-a5c2-952c5e6fc1f2)
I really understand why this should only be available on secured environment since it can access the clipboard via javascript.
I'm really not an expert on how to make a network address accessible via https, but I think it would solve the problem.

**Comment by nicolasprigent** [comment]
Maybe this could help : https://jsavoie.github.io/2021/06/01/letsencrypt.html

**Comment by programspace** [comment]
Thank you for your quick response.
As I expected, it doesn't work on HTTP...
Sorry for the trouble.  Thanks!

**Comment by nicolasprigent** [comment]
no problem, I've made an update on the readme.txt of my plugin.
