### ISSUE TITLE
Jump to top when copying on mobile

### ISSUE THREAD

**Issue by AnonTester** [nicolasprigent/Dokuwiki-Copycode-plugin#2]
In version 2020-07-01, when clicking to copy the code block on a mobile phone (android), the window jumps to the top.

Also, as a feature request/suggestion, rather than the whole code box being a link target to copy the code, I think it would be better if there was a button on the top right above the code box to copy the code. This enables being able to select or copy part of the codebox code rather than it being copied completely immediately and also prevents accidental overwrite of existing clipboard content.

**Comment by nicolasprigent** [comment]
Hi, thanks for the interest in this plugin.

I will try to find what's going on when copying the code block on android.

For the button suggestion, I think I wouldn't go that way because I wanted the plugin to be as much straight forward that it could be. Instead, I will try to investigate an other solution : if the user selects some text in the code block, it's that text that is copied, and if it's only a click, it's the entire block that is copied. What do you think ?
Also, if you really want the button on top of the text block, there's other plugins that can do the job (I think of this one for example : https://www.dokuwiki.org/plugin:codeclipboard)

For the accidental click situation, maybe I could add a button in the infobox to "cancel" the copy ? But to do so I will have to save the clipboard temporarly, this could add some security issues (I don't know if it's even possible). If not possible, I will have to add an extra step to the copy : "Click", then "Confirm copy".

**Comment by AnonTester** [comment]
Hi, thanks for your response. 

I wasn't aware of the codeclipboard plugin, but found that one shortly after sending the suggestion and I'm using it now as it suits my use case better.

As for your suggestion, I guess that could work, but don't spend any time working on that if you're not interested in that functionality yourself or if your use case is different.

Thanks though and I hope you figure out why the window jumps to the top on Android. (the codeclipboard plugin doesn't)

**Comment by nicolasprigent** [comment]
Hi @AnonTester ,
I updated the plugin to add the code selection copy. I also refactored my script to use navigator "copy to clipboard" internal functionnality, it has solved the jump issue on android, but may not work on older navigators (well, really old ones :) ). I haven't adressed the issue about accidental click for now but I'll think of it later I guess. If you find some time to test it, I'd like to know if you find this new version usefull.
